### ISSUE TITLE
Refactor price calculations

### ISSUE THREAD

**Issue by zarazan** [ojo-network/price-feeder#105]
The order of operations when calculating prices can be optimized making it faster and easier to read.

**Current order of operations:**
1. Loop converting candles to USD
  a. Find pairs to convert with
  b. Filter deviations for conversion pair
    i. Calculate TVWAP per provider
    ii. Filter all prices outside standard deviation
  c. Compute TVWAP for conversion pairs and calc conversion rate
  d. Loop over all candles converting them to USD using conversion rate
2. Filter candle deviations per provider/pair
3. Compute TVWAPS per provider (only used for REST API)
4. Compute TVWAPS per pair
(If there are zero TVWAP prices repeat the same logic for Tickers)

**Suggested order of operations:**
1. Compute TVWAPS per provider/pair
2. Filter provider/pairs that are outside the standard deviation (save full list for REST API)
3. Compute TVWAPS per pair
4. Convert to USD for non-USD TVWAPS

The suggested way would substantially decrease the number of times we do currency conversions and computation of TVWAPs.

When refactoring these functions we should consider adding information about both the quote AND base denoms related to the price stored in `AggregatedProviderCandles` and `AggregatedProviderPrices`. It will make writing the convert function much easier and resolve this issue: https://github.com/ojo-network/price-feeder/issues/108

**Refactor Steps:**
1. Improve integration test to check final price-feeder prices against coingecko
  a. Add make command for running it
2. PR to Add base and quote denom information to stored prices as described above
3. PR to update the order we compute TVWAPS/TWAPS and convert prices to USD

**Comment by adamewozniak** [comment]
@zarazan I'm pretty sure this and #108 are finished up
