### ISSUE TITLE
Separate out price feeder provider config file

### ISSUE THREAD

**Issue by adamewozniak** [ojo-network/price-feeder#124]
## Problem Definition

Each time we release a new price feeder config version, validators have to re-configure the rest of their settings (especially their keyring)

This proposes that we separate out the providers into its own file so that they can just clone that each new asset listing and not have to mess around with their regular settigns.

---

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adamewozniak** [comment]
Suggested featureset: https://linear.app/umee/issue/UMEE-598/refactor-price-feeder-config

**Comment by zarazan** [comment]
Read my mind.
