### ISSUE TITLE
Categories errors more accurately 

### ISSUE THREAD

**Issue by marcmat** [ojo-network/price-feeder#226]
Price feeder right now uses only 2 times of logs - info and error. Some errors might be ignores for instance lack of provider, but some errors like for instance "cant get price" should be fatals.

PF requires code review with logs + errors assessment:
info - general info
debug - info for devs
warn - minor issue - issues that should be reviewed within 1 week
error - major issue -  issues that should be reviewed within 1 day
fatal - showstopper - pagerduty alert

**Comment by zarazan** [comment]
I'm with you, the price-feeder log is crazy. I just downgraded a few errors to warnings here: https://github.com/ojo-network/price-feeder/pull/210/files. Do you have any other specific examples. One thing I'd like to improve on soon that is somewhat related is reducing the number of errors and warnings we output when it starts up that are unnecessary.
